from pages.form_page import FormPage
import time
from selenium.webdriver.common.keys import Keys


def test_login_form(browser):
    page = FormPage(browser)
    page.visit()
    assert not page.modal_dialog.exist()
    page.btn_submit.scroll_to_element()
    page.first_name.send_keys('Tester')
    page.last_name.send_keys('Testosteronovich')
    page.user_email.send_keys('lublu@fgds.com')
    page.gender_radio_1.click()
    page.user_number.send_keys('8005553535')
    page.hobbies_music.click()
    page.current_address_textarea.send_keys('Kukuevo')
    page.select_state.click_force()
    time.sleep(1)
    page.select_state_textarea.send_keys(Keys.DOWN)
    page.select_state_textarea.send_keys(Keys.DOWN)
    page.select_state_textarea.send_keys('Raj')
    time.sleep(1)
    page.select_state_textarea.send_keys(Keys.ENTER)
    time.sleep(1)
#     page.select_state_textarea.find_element().send_keys(Keys.TAB, Keys.DOWN, Keys.DOWN, Keys.ENTER)
#     time.sleep(1)
#     page.select_state_textarea.send_keys(Keys.DOWN)
#     b = page.fantom_locator_2.find_element()
#     a = page.fantom_locator.find_element()
#     page.fantom_locator.click_force()
    page.select_city_textarea.send_keys(Keys.DOWN)
    page.select_city_textarea.send_keys('Jaipur')
    page.select_city_textarea.send_keys(Keys.ENTER)
    time.sleep(3)
    page.btn_submit.click_force()
    time.sleep(2)
    assert page.modal_dialog.exist()
    page.btn_close_modal.click()
    time.sleep(1)
    assert not page.modal_dialog.exist()
